from .mlstm_chunkwise_parallel_bw_dK import mlstm_chunkwise_parallel_bw_dK_metal
from .mlstm_chunkwise_parallel_bw_dQ import mlstm_chunkwise_parallel_bw_dQ_metal
from .mlstm_chunkwise_parallel_bw_dV import mlstm_chunkwise_parallel_bw_dV_metal
from .mlstm_chunkwise_recurrent_bw_dC import mlstm_chunkwise_recurrent_bw_dC_metal
